default: &default
  adapter: postgresql
  encoding: unicode
  timeout:  5000
  pool: <%= ENV.fetch("DB_CONNECTION_POOL_SIZE", 45).to_i %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] %>
